version: "3"
services:
  api:
    build: "."
    args:
      - CACHEBUST=${BUILD_DATE}
    image: "${DJANGO_TUTORIAL_API_IMAGE}"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 80
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: "${DJANGO_TUTORIAL_NGINX_IMAGE}"
    ports:
      - 80:80
