version: "3"
services:
  api:
    container_name: "django-api"
    image: "${DJANGO_TUTORIAL_API_IMAGE}"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    expose:
      - 80
  nginx:
    container_name: "nginx"
    image: "${DJANGO_TUTORIAL_NGINX_IMAGE}"
    ports:
      - 80:80
    volumes:
      - static_volume:/store/staticfiles/
      - media_volume:/store/mediafiles/
volumes:
  static_volume:
  media_volume:
