version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: "False"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
volumes:
  static_volume:
  media_volume:
