version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "sudo kill $(ps aux | grep gunicorn | grep -v grep | awk '{print $2}')
            python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --daemon"

    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "django-insecure-j2#*0xj=vjaebcr_3h6e&ug@bgj)nahr&icw!s2##@2g$94e21"
      DEBUG: "False"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
volumes:
  static_volume:
  media_volume:
