version: "3"
services:
  api:
    container_name: "django-api"
    image: "${DJANGO_TUTORIAL_API_IMAGE}"
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/static/
      - media_volume:/media/
      - data:/data/
    expose:
      - 80
  nginx:
    container_name: "nginx"
    image: "${DJANGO_TUTORIAL_NGINX_IMAGE}"
    ports:
      - 80:80
    volumes:
      - static_volume:/static/
      - media_volume:/media/
      - data:/data/
volumes:
  static_volume:
  media_volume:
  data:
